### ISSUE TITLE
batterypower@joka42 

### ISSUE THREAD

**Issue by ptandler** [joka42/cinnamon-spices-applets#2]
```
 * Applet version/Build date  commit 51e64aa4691aad942225ddf5cec4ca5006796eb1
 * Cinnamon version 5.0.7
 * Distribution - Mint 20.2, kernel 5.11.0
 ```

@joka42 

**Issue**

In your applet you use
 ```js
        const currentDrawFile = "/sys/class/power_supply/BAT0/current_now";
        const voltageDrawFile = "/sys/class/power_supply/BAT0/voltage_now";
 ```

However, on my system there is no `current_now`:

 ```bash
❯ ls /sys/class/power_supply/BAT0
alarm           energy_full_design  power_now      type
capacity        energy_now          present        uevent
capacity_level  hwmon2              serial_number  voltage_min_design
cycle_count     manufacturer        status         voltage_now
device          model_name          subsystem
energy_full     power               technology
 ```

I didn't test it yet, but I guess if these entries are missing, it won't work? And I've no idea what else should be used instead and how portable these things are ...

And BTW: What should happen in case there are several batteries? They should be added, or?

When I attach my keyboard, it seems to be listed as battery as well, no idea why :-)

 ```
 ❯ ls /sys/class/power_supply/
AC0  BAT0  hid-0018:04F3:2A45.0001-battery
❯ cat /sys/class/power_supply/hid-0018:04F3:2A45.0001-battery/model_name
ELAN9008:00 04F3:2A45
❯ cat /sys/class/power_supply/hid-0018:04F3:2A45.0001-battery/type
Battery
```

**Comment by joka42** [comment]
**Different files in /sys/class/power_supply/BAT0/**
I don't have a better solution to make it work on any system. Can you check if power_now contains what I would assume it contains, the power drawn from the batter in uW? I'd add that to the applet in case other systems have the same configuration and add a hint if they have a configuration that is not handled, yet.

**Multiple Batteries**
I though about that Issue, but I assumed that most laptops will work with 1 battery and handle the rest when someone files an issue for that, I don't have a system to test that scenario. Maybe a Microsoft Surface Book or something like that falls into that niche... Until then, I'd use the ostrich algorithm to deal with the problem ;-).
Anyway, regarding your keyboard, is it cable-connected or does it have a battery? I'd assume that you could check the battery for the keyboard in Linux. That would explain why it appears there. However, for the applet, it is not interesting, so I will just ignore it.

**Comment by ptandler** [comment]
According to [this answer](https://unix.stackexchange.com/a/75684/224565), `cat /sys/class/power_supply/BAT0/power_now` returns power measured in microwatts. But some users report there that they don't have `/sys/class/power_supply` at all or that it's empty.

[Here](https://unix.stackexchange.com/a/68537/224565) "On Thinkpads if the `tp_smapi` module is loaded, the file is `cat /sys/devices/platform/smapi/BAT0/power_now`"

Looks like that there are a couple of different methods in different systems :frowning_face: 

https://www.simplified.guide/linux/view-battery-information lists two other methods beside `/sys`
to query the ACPI (Advanced Configuration and Power Interface) daemon: `upower` is installed on my system, `acpi` is not installed.

Did you check how the `power@cinnamon.org` applet is querying battery information?

WRT my keyboard: it's cable connected and I absolutely have no idea _why_ it is listed as battery. It definitively _should_ be ignored :smirk:

**Comment by joka42** [comment]
@ptandler 

upower seems to be the way to go. However, its update rate is very low.  There is a solution here: https://askubuntu.com/questions/878556/get-battery-status-to-update-more-often-or-on-ac-power-wake

If I have time in the next days I will look into it and hope that it does not increase the power consumption too much if upower updates every second instead of once a minute or so.

**Comment by joka42** [comment]
@ptandler 
I added support for upower, if the files do not exist. It seems to be very expensive:
When only reading from files, I idle at around 5 W on my notebook, when I use upower, power consumption increases to 6.5 (nothing else has changes on the system.) 
It might not be a problem with upower but with invoking the python script to refresh upower data.

Anyway, the issue should be fixed for all systems now.
